In [1]:
notlar = [85, 92, 76, 92, 100, 76, 85, 92]
benzersiz = list(set(notlar))

en_yuksek = max(notlar)
en_dusuk = min(notlar)

sirali = sorted(notlar)

print("Benzersiz:", benzersiz)
print("En yüksek:", en_yuksek)
print("En düşük :", en_dusuk)
print("Sıralı   :", sirali)

Benzersiz: [100, 92, 85, 76]
En yüksek: 100
En düşük : 76
Sıralı   : [76, 76, 85, 85, 92, 92, 92, 100]


In [3]:
def armstrong_mu(n):
    toplam = sum(int(h)**3 for h in str(n))
    return toplam == n

sayi = int(input("Bir sayı girin: "))
if armstrong_mu(sayi):
    print(sayi, "Armstrong sayısıdır ")
else:
    print(sayi, "Armstrong sayısı değildir ")



Bir sayı girin:  66


66 Armstrong sayısı değildir 


In [4]:
A = {"Python", "R", "SQL", "Java"}
B = {"C++", "Python", "JavaScript", "SQL"}

ortak = A & B
sadece_A = A - B
birlesim_alfabetik = sorted(A | B)

print("Ortak diller:", ortak)
print("Sadece A'da:", sadece_A)
print("Birleşim (alfabetik):", birlesim_alfabetik)

Ortak diller: {'SQL', 'Python'}
Sadece A'da: {'R', 'Java'}
Birleşim (alfabetik): ['C++', 'Java', 'JavaScript', 'Python', 'R', 'SQL']


In [5]:
import random, statistics

random.seed(42)
sayilar = [random.randint(1, 100) for _ in range(10)]
ortalama = statistics.mean(sayilar)
st_sapma = statistics.pstdev(sayilar)

print("Rastgele sayılar:", sayilar)
print("Ortalama:", ortalama)
print("Standart sapma:", st_sapma)

Rastgele sayılar: [82, 15, 4, 95, 36, 32, 29, 18, 95, 14]
Ortalama: 42
Standart sapma: 33.250563904992646


In [6]:
from collections import Counter
import re

def kelime_sayaci(metin):
     kelimeler = re.findall(r"[\wçğıöşüÇĞİÖŞÜ]+", metin.lower())
     if not kelimeler:
         return (0, None, None)
     toplam = len(kelimeler)
     en_uzun = max(kelimeler, key=len)
     en_sik = Counter(kelimeler).most_common(1)[0][0]
     return toplam, en_uzun, en_sik

metin = input("Metin girin: ")
print(kelime_sayaci(metin))




Metin girin:  bugun sabah cok erken uyandım. veri bilimi dersime girmeden once güzel bir kahvaktıya yaptım. dersim oldukça verimli geçti. dersten sonra kendimi dizi izlerken buldum. 3. bölümüne geldiğimde telefonuma bir arama düştü. arayan kuzenim sevdaydı. bana bir iş fırsatı buldugunu pazartesi günü görüşmeye gitmemi soyledi. umarım benim için hayırlı olan beni bulur sevgilerimle


(52, 'sevgilerimle', 'bir')


In [7]:
sayilar = [5, 12, 7, 18, 24, 3, 16]

ciftler = list(filter(lambda x: x % 2 == 0, sayilar))
kareler = list(map(lambda x: x*x, ciftler))
azalan = sorted(kareler, reverse=True)

print("Çift sayılar:", ciftler)
print("Kareleri:", kareler)
print("Azalan:", azalan)

Çift sayılar: [12, 18, 24, 16]
Kareleri: [144, 324, 576, 256]
Azalan: [576, 324, 256, 144]


In [8]:
kelimeler = ["veri", "bilim", "analiz", "yapayzeka", "python"]
sirali = sorted(kelimeler, key=lambda k: len(k))
print(sirali)

['veri', 'bilim', 'analiz', 'python', 'yapayzeka']


In [11]:
import re

def rakamlari_topla(s):
    sayilar = re.findall(r"\d+", s)
    return sum(map(int, sayilar)) if sayilar else 0

s = input("Bir string girin: ")
print("Rakamların toplamı:", rakamlari_topla(s))


Bir string girin:  Bugün 2 kere 15 dk yürüdüm ve 3 kere 10 dk koştum


Rakamların toplamı: 30


In [12]:
import numpy as np
np.random.seed(7)

dizi = np.random.randint(0, 51, size=10)
print("Dizi:", dizi.tolist())
print("Ortalama:", float(np.mean(dizi)))
print("Std sapma:", float(np.std(dizi)))
print("En büyük:", int(np.max(dizi)))

Dizi: [47, 4, 25, 3, 19, 23, 39, 28, 14, 23]
Ortalama: 22.5
Std sapma: 13.10152662860325
En büyük: 47


In [13]:
np.random.seed(21)
matris = np.random.rand(5,5)

sutun_ort = matris.mean(axis=0)
binary = (matris > 0.5).astype(int)

print("Matris:\n", matris)
print("Sütun ortalamaları:", sutun_ort)
print("Binary matris:\n", binary)

Matris:
 [[0.04872488 0.28910966 0.72096635 0.02161625 0.20592277]
 [0.05077326 0.30227189 0.66391029 0.30811439 0.58359128]
 [0.06957095 0.86740448 0.13324052 0.17812466 0.49592955]
 [0.86369964 0.75894384 0.97048513 0.75930255 0.38425003]
 [0.40871833 0.71336043 0.27066977 0.85410287 0.91316397]]
Sütun ortalamaları: [0.28829741 0.58621806 0.55185441 0.42425215 0.51657152]
Binary matris:
 [[0 0 1 0 0]
 [0 0 1 0 1]
 [0 1 0 0 0]
 [1 1 1 1 0]
 [0 1 0 1 1]]


In [14]:
from statistics import mean, pstdev
from collections import defaultdict, Counter
import random

kitaplar = [
 {"isim": "Veri Bilimi 101", "yazar": "Ali", "tur": "Bilim", "satis": 1200, "yil": 2021},
 {"isim": "Python ile Yapay Zeka", "yazar": "Ayşe", "tur": "Bilim", "satis": 950, "yil": 2020},
 {"isim": "İstatistik Temelleri", "yazar": "Ali", "tur": "Akademik", "satis": 700, "yil": 2019},
 {"isim": "Makine Öğrenmesi", "yazar": "Can", "tur": "Bilim", "satis": 1800, "yil": 2022},
 {"isim": "Veri Görselleştirme", "yazar": "Deniz", "tur": "Sanat", "satis": 400, "yil": 2018},
 {"isim": "Matematiksel Modelleme", "yazar": "Ali", "tur": "Akademik", "satis": 1500, "yil": 2021},
 {"isim": "Bilgi Toplumu", "yazar": "Ayşe", "tur": "Sosyal", "satis": 600, "yil": 2022}
]

def en_cok_satan(kitaplar):
    return max(kitaplar, key=lambda k: k["satis"])

def yazar_satislari(kitaplar):
    sonuc = defaultdict(int)
    for k in kitaplar:
         sonuc[k["yazar"]] += k["satis"]
    return dict(sonuc)


turler = {k["tur"] for k in kitaplar}
bin_ustu_isimler = [k["isim"] for k in kitaplar if k["satis"] > 1000]


sonrasi_2020 = list(filter(lambda k: k["yil"] > 2020, kitaplar))
satis_artis_10 = list(map(lambda k: {**k, "satis": int(round(k["satis"]*1.10))}, kitaplar))
azalan_satis = sorted(kitaplar, key=lambda k: k["satis"], reverse=True)


ortalama_satis = mean([k["satis"] for k in kitaplar])
tur_sayac = Counter()
for k in kitaplar:
    tur_sayac[k["tur"]] += k["satis"]
en_cok_satan_tur = tur_sayac.most_common(1)[0][0]
std_sapma = pstdev([k["satis"] for k in kitaplar])

random.seed(123)
train_size = int(round(len(kitaplar)*0.7))
train = random.sample(kitaplar, k=train_size)
test = [k for k in kitaplar if k not in train]

yazar_satis_list = defaultdict(list)
for k in train:
    yazar_satis_list[k["yazar"]].append(k["satis"])
yazar_ort = {y: mean(sat) for y, sat in yazar_satis_list.items()}

test_sonuclari = []
for k in test:
    ort = yazar_ort.get(k["yazar"], ortalama_satis)
    test_sonuclari.append({
        "isim": k["isim"],
        "yazar": k["yazar"],
        "satis": k["satis"],
        "karsilastirma_ort": ort,
        "uzerinde_mi": k["satis"] > ort
    })

print("En çok satan kitap:", en_cok_satan(kitaplar)["isim"])
print("Yazar satışları:", yazar_satislari(kitaplar))
print("Türler:", turler)
print("1000’den fazla satan kitaplar:", bin_ustu_isimler)
print("Ortalama satış:", round(ortalama_satis,1))
print("Standart sapma:", round(std_sapma,1))
print("En çok satış yapan tür:", en_cok_satan_tur)
print("Train seti:", [k["isim"] for k in train])
print("Test seti:", [k["isim"] for k in test])
print("Yazar ortalamaları (train):", {y: round(v,1) for y,v in yazar_ort.items()})
print("Test sonuçları:")
for r in test_sonuclari:
    print(f" - {r['isim']} ({r['yazar']}): satış={r['satis']}, ortalama={round(r['karsilastirma_ort'],1)}, üzerinde_mi={r['uzerinde_mi']}")
    

En çok satan kitap: Makine Öğrenmesi
Yazar satışları: {'Ali': 3400, 'Ayşe': 1550, 'Can': 1800, 'Deniz': 400}
Türler: {'Sanat', 'Akademik', 'Bilim', 'Sosyal'}
1000’den fazla satan kitaplar: ['Veri Bilimi 101', 'Makine Öğrenmesi', 'Matematiksel Modelleme']
Ortalama satış: 1021.4
Standart sapma: 468.9
En çok satış yapan tür: Bilim
Train seti: ['Veri Bilimi 101', 'İstatistik Temelleri', 'Bilgi Toplumu', 'Makine Öğrenmesi', 'Python ile Yapay Zeka']
Test seti: ['Veri Görselleştirme', 'Matematiksel Modelleme']
Yazar ortalamaları (train): {'Ali': 950, 'Ayşe': 775, 'Can': 1800}
Test sonuçları:
 - Veri Görselleştirme (Deniz): satış=400, ortalama=1021.4, üzerinde_mi=False
 - Matematiksel Modelleme (Ali): satış=1500, ortalama=950, üzerinde_mi=True
